### PR TITLE
Add python text interface program thing

### PR DESCRIPTION
**Pull request by antonijn**
Gets most of the game rules right. Enter 'h' command for help.

### CODE REVIEW

**Comment by antonijn** [comment]
4 space indents are tyranny

**Review by a-t-0 — APPROVED** [review]
Wonderful!

It would be nice if
- [ ] The rules could be stored in a separate `rules.py`.
- [ ] The code is commented so that it is as easy as possible for new people looking at it to understand how it works:)

I'll work on the commenting, and will let you know when I get to the `rules.py` refactor.

**Comment by antonijn** [comment]
What kind of rules would you like to be able to set?

**Comment by a-t-0** [comment]
> uld you like to be able to set?

I think for `ruleset0`, the basic ruleset would be appropriate.
https://images.zmangames.com/filer_public/d5/20/d5208d61-8583-478b-a06d-b49fc9cd7aaa/zm7810_carcassonne_rules.pdf

**Comment by antonijn** [comment]
> Maybe a miscomunnication occurs, where I assume the rules to include the scoring, whereas perhaps you perceived the rules to merely include whether a tile/item can be placed? Do you think it would make sense to include the scoring in the ruleset?

Well, what part of the ruleset might be variable at all? Obviously if everything is variable, then you could end up with a ruleset defining chess rather then Carcassonne... Is it just scoring, min/maximum number of players, number of meeples in initial supply?

**Comment by a-t-0** [comment]
> bviously if everything is va

I think all parts of the ruleset are subject to change, depending on which extension pack is played (that includes the number of meeples/puppets to play with in initial supply, and scoring, and min/max nr of players). And in retrospect, I think it the rules define how the scoring is done, so I think it would improve the structure if the scoring is also included in the rules.

**Comment by antonijn** [comment]
Probably makes sense to have a data structure containing that kinda stuff along with some defaults, and have a cmd line option where you can specify a json file or sth

**Comment by a-t-0** [comment]
> Probably makes sense to have a data structure containing that kinda stuff along with some defaults, and have a cmd line option where you can specify a json file or sth. Makes more sense to me than to refactor the rules into a separate file you'd have to edit each time.

Yes. Though, I don't think one should have to edit the ruleset "every gameplay". I thought one should simply be able to select a ruleset when starting the game, where the basic game uses the basic ruleset by default, unless specified otherwise. I think for most people it would be more intuitive to be able to write the rules in python logic than in a JSON file. 

Also, since it now seems more sensible (if you agree) to have files like:
`ruleset0.py`
`ruleset1.py`
Etc. The branch should be renamed to build0, instead of build0rule0. This lowers the amount of branches, and ensures less switching of branches is required if someone wants to run an agent in a different ruleset. (At the cost of having more rule-files).

**Comment by antonijn** [comment]
This isn't really how comparable programs/protocols do it. I know that with Katago, for instance, a default rule set is selected based on your personal config file, but you can edit it through the command line interface.

Wouldn't it make more sense to have `standard_rules.json`, `strange_rules.json`, `meeple_anarchy.json` etc. (similar to how we have a `tiles.png` at the moment), and to set those via either a cmd line option (makes most sense to me), or alternatively as the first command in the command line interface. Maybe at some point add a feature so that the default rule set can be selected through a `~/.config/csonne/user.conf` file.

And from an end user perspective, what would be the difference between executing `./strange_rules.py` or `./csonne -r strange_rules`? Either way, you'll have to select a ruleset "when starting the game", i.e. each time you invoke the programme. Except with JSON, specification of a user default ruleset (through user config file) becomes much easier.

**Comment by a-t-0** [comment]
> This isn't really how comparable programs/protocols do it. I know that with Katago, for instance, a default rule set is selected based on your personal config file, but you can edit it through the command line interface.
> 
> Wouldn't it make more sense to have `standard_rules.json`, `strange_rules.json`, `meeple_anarchy.json` etc. (similar to how we have a `tiles.png` at the moment), and to set those via either a cmd line option (makes most sense to me), or alternatively as the first command in the command line interface. Maybe at some point add a feature so that the default rule set can be selected through a `~/.config/csonne/user.conf` file.
> 
> And from an end user perspective, what would be the difference between executing `./strange_rules.py` or `./csonne -r strange_rules`? Either way, you'll have to select a ruleset "when starting the game", i.e. each time you invoke the programme. Except with JSON, specification of a user default ruleset (through user config file) becomes much easier.

I agree the names of the rulesets make more sense.  Also the config option seems sensible. On the JSON specification, for me that becomes more difficult than in python. But this is why we have different builds and different rulesets, this is your party, and I'm the guest so please go for the JSON option as you envision it! Sorry to hold you back for this long, nice to have clarified the different perspectives!

**Pull request merged**
